-- 04-enable-rls.sql
-- Enable Row Level Security (RLS) on relevant tables

ALTER TABLE IF EXISTS users  ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS files  ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS dashboards  ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS charts  ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS usage_logs  ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS plans ENABLE ROW LEVEL SECURITY;
